import { Inject, Injectable, Logger } from '@nestjs/common';
import { Contact } from '../../../shared/entities/contact.entity.js';
import { ContactRepositoryPort, CONTACT_REPOSITORY_PORT } from '../domain/ports/contact-repository.port.js';
import { DataValidationService, RawContactData } from './data-validation.service.js';
import { DataModelingService } from '../domain/services/data-modeling.service.js';
import { EmbeddingService } from '../../../shared/services/embedding.service.js';

@Injectable()
export class IngestContactsService {
  private readonly logger = new Logger(IngestContactsService.name);

  constructor(
    @Inject(CONTACT_REPOSITORY_PORT)
    private readonly contactRepository: ContactRepositoryPort,
    private readonly validationService: DataValidationService,
    private readonly modelingService: DataModelingService,
    private readonly embeddingService: EmbeddingService,
  ) {}

  /**
   * Processes and saves contact records
   * Returns count of successfully ingested contacts
   */
  async ingestContacts(
    rawContacts: RawContactData[],
    userId: string,
  ): Promise<{ successCount: number; errorCount: number; errors: string[] }> {
    const errors: string[] = [];
    const validContacts: Contact[] = [];
    const contactEmbeddings: Map<number, number[]> = new Map(); // Map index to embedding

    for (let i = 0; i < rawContacts.length; i++) {
      const rawContact = rawContacts[i];
      const validation = this.validationService.validateRequiredFields(rawContact);
      if (!validation.valid) {
        errors.push(
          `Invalid contact ${rawContact.firstName} ${rawContact.lastName}: ${validation.errors.join(', ')}`,
        );
        continue;
      }

      try {
        const contact = this.modelingService.mapToContact(rawContact, userId);

        // Check if contact already exists (by URL)
        if (contact.url) {
          const existing = await this.contactRepository.findByUserIdAndUrl(userId, contact.url);
          if (existing) {
            this.logger.debug(`Contact already exists: ${contact.url}`);
            continue; // Skip duplicates
          }
        }

        // Store embedding mapping if provided
        if (rawContact.embedding && rawContact.embedding.length === 768) {
          contactEmbeddings.set(validContacts.length, rawContact.embedding);
        }

        validContacts.push(contact);
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : 'Unknown error';
        errors.push(`Error mapping contact ${rawContact.firstName} ${rawContact.lastName}: ${errorMsg}`);
        this.logger.error(`Error mapping contact`, error);
      }
    }

    // Batch save valid contacts
    let successCount = 0;
    if (validContacts.length > 0) {
      try {
        const saved = await this.contactRepository.saveMany(validContacts);
        successCount = saved.length;

        // Generate and update embeddings for contacts that don't have them
        // profile_text is auto-generated by the database, so we can use it for embedding
        const contactsNeedingEmbeddings: Array<{ contact: Contact; profileText: string }> = [];
        
        for (let i = 0; i < saved.length; i++) {
          const contact = saved[i];
          const providedEmbedding = contactEmbeddings.get(i);
          
          if (providedEmbedding) {
            // Use provided embedding
            try {
              await this.contactRepository.updateEmbedding(contact.id, providedEmbedding);
              this.logger.debug(`Updated embedding for contact ${contact.id} (provided)`);
            } catch (embeddingError) {
              const errorMsg = embeddingError instanceof Error ? embeddingError.message : 'Unknown error';
              errors.push(`Error updating embedding for contact ${contact.firstName} ${contact.lastName}: ${errorMsg}`);
              this.logger.error(`Error updating embedding`, embeddingError);
            }
          } else {
            // Generate embedding from profile_text (position @ company)
            // profile_text is generated column: position || ' @ ' || company
            const profileText = [contact.position, contact.company]
              .filter(Boolean)
              .join(' @ ') || '';
            
            if (profileText.trim().length > 0) {
              contactsNeedingEmbeddings.push({ contact, profileText });
            }
          }
        }

        // Generate embeddings in batch for contacts that need them
        if (contactsNeedingEmbeddings.length > 0) {
          try {
            const texts = contactsNeedingEmbeddings.map(item => item.profileText);
            const embeddings = await this.embeddingService.generateEmbeddingsBatch(texts);
            
            for (let i = 0; i < contactsNeedingEmbeddings.length; i++) {
              const { contact } = contactsNeedingEmbeddings[i];
              const embedding = embeddings[i];
              
              try {
                await this.contactRepository.updateEmbedding(contact.id, embedding);
                this.logger.debug(`Generated and updated embedding for contact ${contact.id}`);
              } catch (embeddingError) {
                const errorMsg = embeddingError instanceof Error ? embeddingError.message : 'Unknown error';
                errors.push(`Error updating generated embedding for contact ${contact.firstName} ${contact.lastName}: ${errorMsg}`);
                this.logger.error(`Error updating generated embedding`, embeddingError);
              }
            }
          } catch (embeddingError) {
            const errorMsg = embeddingError instanceof Error ? embeddingError.message : 'Unknown error';
            this.logger.warn(`Failed to generate embeddings for ${contactsNeedingEmbeddings.length} contacts: ${errorMsg}`);
            // Don't fail the entire ingestion if embedding generation fails
            // Contacts are saved, embeddings can be generated later
          }
        }

        this.logger.log(`Successfully ingested ${successCount} contacts for user ${userId}`);
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : 'Unknown error';
        errors.push(`Error saving contacts: ${errorMsg}`);
        this.logger.error(`Error saving contacts`, error);
      }
    }

    return {
      successCount,
      errorCount: errors.length,
      errors,
    };
  }
}

