import { Injectable, Inject, Optional } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Contact } from '../../../../shared/entities/contact.entity.js';
import { BaseWorkspaceRepository } from '../../../../shared/repositories/base-workspace-repository.js';
import {
  ContactRepositoryPort,
  PaginatedResult,
} from '../../domain/ports/contact-repository.port.js';
import { WorkspaceResolverService } from '../../../../shared/services/workspace-resolver.service.js';

// Injection token for workspaceId
export const WORKSPACE_ID_TOKEN = 'WorkspaceId';

@Injectable()
export class PostgresContactAdapter extends BaseWorkspaceRepository<Contact> implements ContactRepositoryPort {
  private workspaceIdPromise: Promise<string> | null = null;

  constructor(
    @InjectRepository(Contact)
    contactRepository: Repository<Contact>,
    @Optional()
    @Inject(WORKSPACE_ID_TOKEN)
    private readonly injectedWorkspaceId: string | Promise<string> | undefined,
    @Optional()
    private readonly workspaceResolver?: WorkspaceResolverService,
  ) {
    // Use a temporary workspaceId - will be resolved lazily
    super(contactRepository, '00000000-0000-0000-0000-000000000000');
  }

  /**
   * Get the actual workspace ID, resolving it if needed
   */
  private async getWorkspaceId(): Promise<string> {
    if (this.injectedWorkspaceId) {
      if (typeof this.injectedWorkspaceId === 'string') {
        return this.injectedWorkspaceId;
      }
      return this.injectedWorkspaceId;
    }

    if (this.workspaceIdPromise) {
      return this.workspaceIdPromise;
    }

    if (this.workspaceResolver) {
      this.workspaceIdPromise = this.workspaceResolver.getPlaceholderWorkspaceId();
      return this.workspaceIdPromise;
    }

    // Fallback to placeholder
    return '00000000-0000-0000-0000-000000000000';
  }

  /**
   * Override save to handle embedding vectors properly
   * TypeORM doesn't natively support vector types, so we use raw SQL for embeddings
   */
  async save(contact: Contact): Promise<Contact> {
    // Resolve workspace ID
    this.workspaceId = await this.getWorkspaceId();
    contact.workspaceId = this.workspaceId;

    // If embedding is provided, we need to use raw SQL
    // For now, save without embedding and update separately if needed
    // Embeddings are typically generated asynchronously after contact creation
    const saved = await this.repository.save(contact);
    return saved;
  }

  /**
   * Override saveMany to handle embedding vectors properly
   */
  async saveMany(contacts: Contact[]): Promise<Contact[]> {
    // Resolve workspace ID
    this.workspaceId = await this.getWorkspaceId();
    
    // Set workspaceId for all contacts
    contacts.forEach(contact => {
      contact.workspaceId = this.workspaceId;
    });

    // Save contacts first (without embeddings)
    // Note: profile_text is automatically generated by the database
    const saved = await this.repository.save(contacts);

    // Note: Embeddings are typically generated asynchronously after contact creation
    // They can be updated later using updateEmbedding() method
    // If embeddings are provided in the contacts, they would need to be stored separately
    // and updated after save, but for now we'll handle embeddings via a separate endpoint

    return saved;
  }

  /**
   * Update embedding for a contact using raw SQL
   * TypeORM doesn't support vector types, so we use raw SQL
   */
  async updateEmbedding(contactId: string, embedding: number[]): Promise<void> {
    if (embedding.length !== 768) {
      throw new Error('Embedding must be 768 dimensions');
    }

    // Resolve workspace ID
    this.workspaceId = await this.getWorkspaceId();

    // Format embedding as PostgreSQL vector literal: '[0.1,0.2,...]'
    const vectorString = '[' + embedding.join(',') + ']';

    // Use pgvector's casting syntax
    await this.repository.query(
      `UPDATE contacts SET embedding = $1::vector WHERE id = $2 AND workspace_id = $3`,
      [vectorString, contactId, this.workspaceId]
    );
  }

  async findByUserIdAndUrl(userId: string, url: string): Promise<Contact | null> {
    // Resolve workspace ID and update the base repository's workspaceId
    this.workspaceId = await this.getWorkspaceId();
    // Base repository automatically filters by workspaceId
    return this.findOne({
      where: { userId, url } as any,
    });
  }

  async findByUserId(userId: string): Promise<Contact[]> {
    // Resolve workspace ID and update the base repository's workspaceId
    this.workspaceId = await this.getWorkspaceId();
    return this.find({
      where: { userId } as any,
      order: { createdAt: 'DESC' },
    });
  }

  async findByUserIdPaginated(
    userId: string,
    page: number,
    limit: number,
  ): Promise<PaginatedResult<Contact>> {
    const skip = (page - 1) * limit;

    // Resolve workspace ID and update the base repository's workspaceId
    this.workspaceId = await this.getWorkspaceId();
    const [data, total] = await this.findAndCount({
      where: { userId } as any,
      order: { createdAt: 'DESC' },
      skip,
      take: limit,
    });

    const totalPages = Math.ceil(total / limit);

    return {
      data,
      total,
      page,
      limit,
      totalPages,
      hasNextPage: page < totalPages,
      hasPreviousPage: page > 1,
    };
  }
}

