import { Column, CreateDateColumn, Entity, Index, ManyToOne, PrimaryGeneratedColumn, JoinColumn } from 'typeorm';
import { User } from './user.entity.js';
import { Workspace } from './workspace.entity.js';

@Entity({ name: 'contacts' })
export class Contact {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Index()
  @Column({ type: 'uuid', name: 'workspace_id' })
  workspaceId!: string;

  @ManyToOne(() => Workspace)
  @JoinColumn({ name: 'workspace_id' })
  workspace?: Workspace;

  @Index()
  @Column({ type: 'uuid', name: 'user_id' })
  userId!: string;

  @ManyToOne(() => User)
  @JoinColumn({ name: 'user_id' })
  user?: User;

  @Column({ type: 'varchar', length: 255, nullable: true, name: 'source_id' })
  sourceId!: string | null;

  @Column({ type: 'varchar', length: 100, nullable: true, name: 'first_name' })
  firstName!: string | null;

  @Column({ type: 'varchar', length: 100, nullable: true, name: 'last_name' })
  lastName!: string | null;

  @Column({ type: 'varchar', length: 255, nullable: true })
  email!: string | null;

  @Column({ type: 'varchar', length: 512, nullable: true })
  url!: string | null;

  @Column({ type: 'varchar', length: 255, nullable: true })
  company!: string | null;

  @Column({ type: 'varchar', length: 255, nullable: true })
  position!: string | null;

  @Column({ type: 'date', nullable: true, name: 'connected_on' })
  connectedOn!: string | null;

  // profile_text is a generated column (computed from position and company)
  // It's automatically generated by the database: position || ' @ ' || company
  // We can read it but should never try to write to it
  @Column({ type: 'text', nullable: true, name: 'profile_text', select: false, insert: false, update: false })
  profileText!: string | null;

  @Column({ type: 'jsonb', nullable: true, name: 'inferred_role' })
  inferredRole!: unknown;

  @Column({ type: 'varchar', length: 100, nullable: true, name: 'inferred_sector' })
  inferredSector!: string | null;

  // Embedding vector (768-dim for text-embedding-3-small)
  // Represented as number[] in TypeScript, stored as vector(768) in PostgreSQL
  @Column({ type: 'varchar', length: 1, nullable: true, select: false, name: 'embedding' })
  embeddingStub?: string | null;

  // Legacy embedding_vector (1536-dim) - kept for backward compatibility
  @Column({ type: 'varchar', length: 1, nullable: true, select: false, name: 'embedding_vector' })
  embeddingVectorStub?: string | null;

  @CreateDateColumn({ type: 'timestamptz', name: 'created_at' })
  createdAt!: Date;
}


